[app]
name = "simple-21"
version = "0.0.1"
host = "localhost"
port = 8000
read_timeout = 5
write_timeout = 10
idle_timeout = 15

[game]
player = 10
room = 5
money = 0
player_session = 15
room_session = 10